---
- name: Display system information
  hosts: all
  gather_facts: true
  tasks:
    - name: Display system information
      debug:
        msg: |
          System Information:
          ------------------
          Hostname: {{ ansible_hostname }}
          Operating System: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Kernel Version: {{ ansible_kernel }}
          Architecture: {{ ansible_architecture }}
          Total Memory: {{ ansible_memtotal_mb }} MB
          Total CPU Cores: {{ ansible_processor_cores }}
